feedback_position_info:
  positive_firm:
  - ['right_arm_degrees', [-55.1, -0.8, 97.1, 6.4, -0.8]]
  - ['left_arm_degrees', [-55.9, 4.8, -98.2, -6.4, 1.9]]
  - ['torso_degrees', [1.5, 1.0, -0.6]]
  - ['neck_degrees', [1.1, 6.0]]
  positive_neutral:
  - ['right_arm_degrees', [99.1, -6.1, 97.0, 5.6, -1.9]]
  - ['left_arm_degrees', [99.1, 6.1, -97.0, -5.6, 1.9]]
  - ['torso_degrees', [-0.6, -2.2, -0.6]]
  - ['neck_degrees', [1.1, 6.0]]
  positive_encouraging:
  - ['right_arm_degrees', [-55.1, -0.8, 97.1, 6.4, -0.8]]
  - ['left_arm_degrees', [-55.9, 4.8, -98.2, -6.4, 1.9]]
  - ['torso_degrees', [1.5, 15.0, -0.6]]
  - ['neck_degrees', [1.1, 6.0]]
  negative_firm:
  - ['right_arm_degrees', [66.3, -4.8, 97.8, 6.6, -1.9]]
  - ['left_arm_degrees', [66.3, 4.8, -97.8, -6.6, 1.9]]
  - ['torso_degrees', [-0.3, -32.6, -0.8]]
  - ['neck_degrees', [1.1, -16.5]]
  negative_encouraging:
  - ['right_arm_degrees', [66.3, -4.8, 97.8, 6.6, -1.9]]
  - ['left_arm_degrees', [66.3, 4.8, -97.8, -6.6, 1.9]]
  - ['torso_degrees', [-0.3, -18.6, -0.8]]
  - ['neck_degrees', [1.1, -16.5]]
  negative_neutral:
  - ['right_arm_degrees', [99.1, -6.1, 97.0, 5.6, -1.9]]
  - ['left_arm_degrees', [99.1, 6.1, -97.0, -5.6, 1.9]]
  - ['torso_degrees', [-0.6, -2.2, -0.6]]
  - ['neck_degrees', [1.1, -19.4]]

exercise_position_info:
  lateral_arm_motion:
    lateral_up:
      right_arm_degrees: [101.2, -89.4, 97.3, 5.8, -1.0]
      left_arm_degrees: [101.2, 89.4, -97.3, -5.8, 1.0]
    lateral_down:
      right_arm_degrees: [101.2, -89.4, 97.3, 5.8, -1.0]
      left_arm_degrees: [101.2, 89.4, -97.3, -5.8, 1.0]
  bicep_arm_motion:
    bicep_up:
      right_arm_degrees: [76.0, -23.0, 83.0, 89.0, 104.5]
      left_arm_degrees: [76.0, 23.0, -83.0, -89.0, -104.5]
    bicep_down:
      right_arm_degrees: [76.0, -23.0, 83.0, 0.7, 104.5]
      left_arm_degrees: [76.0, 23.0, -83.0, -0.7, -104.5]