angle_info:
  right_shoulder: [right_hip, right_shoulder, right_elbow]
  left_shoulder: [left_hip, left_shoulder, left_elbow]
  right_elbow: [right_shoulder, right_elbow, right_wrist]
  left_elbow: [left_shoulder, left_elbow, left_wrist]

angle_order:
  right_shoulder: [0, 1, 2]
  left_shoulder: [3, 4, 5]
  right_elbow: [6, 7, 8]
  left_elbow: [9, 10, 11]

exercise_info:
  bicep_curls:
    segmenting_joints:
      - [right_elbow, 0]
      - [left_elbow, 0]
    comparison_joints:
      - [right_shoulder, [0, 1, 2]]
      - [left_shoulder, [0, 1, 2]]
      - [right_elbow, [0, 1, 2]]
      - [left_elbow, [0, 1, 2]]
    threshold1: 7500
    threshold2: 10000
    segmenting_joint_inds: []
    current_angles_min: 50
    max_grad: 200
    max_in_range: 130
  lateral_raises:
    segmenting_joints:
      - [right_shoulder, 2]
      - [left_shoulder, 2]
    comparison_joints:
      - [right_shoulder, [0, 1, 2]]
      - [left_shoulder, [0, 1, 2]]
      - [right_elbow, [0, 1, 2]]
      - [left_elbow, [0, 1, 2]]
    threshold1: 7500
    threshold2: 12500
    segmenting_joint_inds: []
    current_angles_min: 35
    max_grad: 200
    max_in_range: 45

neutral_expressions:
  - [0.1, 0, 0, 0, 0, 0]
  - [0.175, 0, 0, 0, 0, 0]
  - [0.25, 0, 0, 0, 0, 0]
  - [0.325, 0, 0, 0, 0, 0]
  - [0.4, 0, 0, 0, 0, 0]

neutral_postures:
  - [-0.2, -1.1, 0, -1.1, 0.2]
  - [-0.2, -1.1, 0, -1.1, 0.2]
  - [0, -1.1, 0, -1.1, 0]
  - [0.2, -1.1, 0, -1.1, -0.2]
  - [0.2, -1.1, 0, -1.1, -0.2]

start_set_smile: [0.3, 0.375, 0.45, 0.525, 0.6]

nonverbal_react:
  positive:
    torso: [0.042, 0.0525, 0.063, 0.0735, 0.084]
    # expression: [0.4, 0.525, 0.65, 0.775, 0.9]
  negative:
    torso: [-0.094, -0.1175, -0.141, -0.1645, -0.188]
    # expression: [0.7, 0.55, 0.4, 0.25, 0.1]

## TODO: REDO based on rospath
# all_messages:
#   bicep_curls:
#     low: !!json /home/roshni/quori_files/quori_ros/src/quori_exercises/exercise_session/bicep_curls_low_edited.json
#     moderate: !!json /home/roshni/quori_files/quori_ros/src/quori_exercises/exercise_session/bicep_curls_moderate_edited.json
#     high: !!json /home/roshni/quori_files/quori_ros/src/quori_exercises/exercise_session/bicep_curls_high_edited.json
#   lateral_raises:
#     low: !!json /home/roshni/quori_files/quori_ros/src/quori_exercises/exercise_session/lateral_raises_low_edited.json
#     moderate: !!json /home/roshni/quori_files/quori_ros/src/quori_exercises/exercise_session/lateral_raises_moderate_edited.json
#     high: !!json /home/roshni/quori_files/quori_ros/src/quori_exercises/exercise_session/lateral_raises_high_edited.json
